name: Validate Gradle Wrapper
on:
    push:
        branches: [main, main-okta]
    pull_request:
        branches: [main, main-okta]

jobs:
    validation:
        name: Validation
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: gradle/wrapper-validation-action@v1
