name: 'UI Tests'
on:
    push:
        branches:
            - "workflow"
jobs:
    check-changes-in-frontend:
        runs-on: ubuntu-latest
        name: Check for changes in frontend
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Get changed files in the frontend folder
              id: changed-files-specific
              uses: tj-actions/changed-files@v34
              with:
                  files: frontend/**

            - name: Run step if any file(s) in the frontend folder change
              if: steps.changed-files-specific.outputs.any_changed == 'true'
              run: echo frontend is affected

            - name: Prevent from running
              if: steps.changed-files-specific.outputs.any_changed == 'true'
              run: exit 1
    run-test:
        name: Run tests and build frontend
        timeout-minutes: 60
        runs-on: ubuntu-latest
        needs: [check-changes-in-frontend]
        steps:
            -   uses: actions/checkout@v3
                with:
                    fetch-depth: 0

            -   name: Setup packages
                working-directory: frontend
                uses: actions/setup-node@v3
                with:
                     node-version: 18
                     cache: 'npm'

            -   name: Install packages
                run: npm ci

            -   name: Run lint
                run: npm run lint

            -   name: Run unit tests
                run: npm run test:unit:ci

            -   name: Run build
                run: npm run build
